// ==UserScript==
// @name         [obj 1] Fresh Foods
// @version      1.7
// @description  Highlights items, price key, added sound & refresh
// @namespace    https://github.com/uxillary/neo-qol
// @author       adamski @uxillary
// @match        https://www.neopets.com/objects.phtml?obj_type=1&type=shop
// @icon         https://www.google.com/s2/favicons?sz=64&domain=neopets.com
// @grant        none
// ==/UserScript==

const refreshKey = 'refreshEnabled'; // Key to track refresh state in localStorage
const minRefreshTime = 4001; // Minimum refresh interval (4 seconds)
const maxRefreshTime = 11601; // Maximum refresh interval (11 seconds)

// Load notification sound
const notificationSound = new Audio("https://raw.githubusercontent.com/uxillary/neo-qol/main/audio/bell-drop.wav");
notificationSound.volume = 0.5;

// Function to start or stop the refresh timer
function toggleRefresh() {
    const refreshEnabled = JSON.parse(localStorage.getItem(refreshKey)) || false;
    if (refreshEnabled) {
        localStorage.setItem(refreshKey, false);
        clearTimeout(refreshTimeout); // Stop refreshing
        refreshButton.textContent = "Start";
        refreshButton.style.backgroundColor = '#007BFF'; // Set button to blue when inactive
    } else {
        localStorage.setItem(refreshKey, true);
        setRandomRefresh(); // Start refreshing
        refreshButton.textContent = "Stop";
        refreshButton.style.backgroundColor = '#28a745'; // Set button to green when active
    }
}

// Function to set a random refresh interval
function setRandomRefresh() {
    if (JSON.parse(localStorage.getItem(refreshKey))) {
        const refreshInterval = Math.floor(Math.random() * (maxRefreshTime - minRefreshTime + 1)) + minRefreshTime;
        refreshTimeout = setTimeout(() => {
            location.reload();
        }, refreshInterval);
    }
}

// Create the refresh toggle button
const refreshButton = document.createElement('button');
refreshButton.style.position = 'fixed';
refreshButton.style.top = '110px';
refreshButton.style.right = '35px';
refreshButton.style.backgroundColor = JSON.parse(localStorage.getItem(refreshKey)) ? '#28a745' : '#007BFF'; // Green if active, blue if inactive
refreshButton.style.color = 'white';
refreshButton.style.padding = '8px 12px';
refreshButton.style.border = 'none';
refreshButton.style.borderRadius = '4px';
refreshButton.style.cursor = 'pointer';
refreshButton.style.fontSize = '12px';
refreshButton.textContent = JSON.parse(localStorage.getItem(refreshKey)) ? "Stop" : "Start";

// Add button click event to toggle the refresh
refreshButton.addEventListener('click', toggleRefresh);
document.body.appendChild(refreshButton);

// Start the refresh timer if enabled
if (JSON.parse(localStorage.getItem(refreshKey))) {
    setRandomRefresh();
}

//change list items here

// List Items < 700 NP 
const List0 = [
  "Acara Day Pancakes",
  "Aisha Cheeseburger",
  "Aisha Riceball",
  "Aisha Toffee Apple",
  "Animal-style Chips",
  "Apple Juice",
  "B-B-Q Pork",
  "Bag of Chips",
  "Banana Milkshake",
  "Beef and Veg Baby Food",
  "Beetroot and Cream Smores",
  "Beetroot Ice Cream",
  "Berry Eyrie Souffle",
  "Bitten Green Apple",
  "Blue Cheese Draik Head",
  "Blue Swirl Cheesicle",
  "Blueberry Jetsam Jelly",
  "Borovan Ice Cream Scoop",
  "Breakfast Croissant",
  "Bubbling Blue Soup",
  "Bug-a-licious Parfait",
  "Buried Treasure Crackers",
  "Burrito in the Wall",
  "Buttered Toast",
  "Can of Neocola",
  "Caramel Acara On A Stick",
  "Carrot Lupe Treat",
  "Caviar Sandwich",
  "Cawl",
  "Cheese Tortilla",
  "Cheeseburger",
  "Cheesy Meat Wrap",
  "Cheesy Popcorn",
  "Cherries",
  "Cherry Milkshake",
  "Cherry Twist Lollypop",
  "Chicken Filets with Fancy Sauce",
  "Chilli Salmon Souffle",
  "Chocolate Coated Tangy Cheese",
  "Chocolate Kougra Pudding",
  "Chocolate Milkshake",
  "Chocolate Sandwich",
  "Chocolately Cheese Wedges",
  "Chocopie Slice",
  "Chokato Crisps",
  "Chokato Kougra Pudding",
  "Churros",
  "Coco NeoCrunch",
  "Coffee",
  "Corn Bread",
  "Crab Spaghetti",
  "Crispies",
  "Crunchy Kacheek Cereal",
  "Deli Turkey Slices",
  "Diet Neocola",
  "Dirt Pie",
  "Dried Chilli Peppers",
  "Dried Squid on a Stick",
  "Durian Biscuit",
  "Edible Smelly Gym Socks",
  "Egg and Tomato Basil",
  "Egg Salad and Cheese Sandwich",
  "Elderberry Achyfi",
  "Endless Salad and Bread Sticks",
  "Extra Crispy Bacon Gum",
  "Extra Sour Seedless Skeem Jam",
  "Fajita Chips",
  "Fish and Chips",
  "Fish Negg Stew",
  "Flaming BBQ Crisps",
  "Forest Fruit Baby Food",
  "Fried Chicken and Waffles",
  "Fried Chicken Breast",
  "Fried Something",
  "Funky Carrot",
  "Garlic Cheese Toast",
  "Giant Chocolette",
  "Gooseberry Tuskaninny Ice Cream",
  "Green Apple",
  "Green Cabbage",
  "Green Grapes",
  "Green Oat Cereal",
  "Gruel Cake",
  "Gruel Pizza",
  "Gummy Pirate Candies",
  "Hasee Puff Cereal",
  "Haunted Woods Chocolate Milk Glass",
  "Hot Banana Soup",
  "Jalapeno Popper",
  "Jetsam Apple Cake",
  "Jetsam Jam",
  "Jhudora Rotten Negg",
  "Juicee",
  "Leaf Taco",
  "Lemon Meringue Baby Food",
  "Lime Negg",
  "Lupe Snack Pack",
  "Mac and Cheese",
  "Mashed Potato With Gravy",
  "Meat Wrap",
  "Mega Tonu Day Burger",
  "Mighty Steakwich",
  "Mint Ice Cream",
  "Molten Hot Chilli",
  "Mynci Cristo Sandwich",
  "Mynci Ham and Cheese Sandwich",
  "Mynci Mushroom Soup",
  "Mynci Veggie Plate",
  "Neggy Custard Pie",
  "Neo Crackers",
  "Orange",
  "Orange Chicken",
  "Pack o Pumpkin Seeds",
  "Pegleg Chicken",
  "Pirate Potato Crisps",
  "Plain Cheesicle",
  "Plain Negg Neggnog",
  "Plain Omurice",
  "Pteri Burger",
  "Pteri Wrap",
  "Purple Carrot",
  "Radish",
  "Rainbow Burger with Cheese",
  "Raspberry Jam",
  "Rose Petal Crisps",
  "Sausage on Toast",
  "Sea Cocktail",
  "Sketch Roast Chicken",
  "Snot Wrap",
  "Spicy Chicken Burrito",
  "Sprinkling of Chilli Pepper",
  "Square Gelatin",
  "Starry Cookie Pile",
  "Starry Crunch",
  "Strawberries and Cream Baby Food",
  "Strawberry and Lime Achyfi",
  "Strawberry Kougra Pudding",
  "Sushi Rolls",
  "Symol White Cheddar Cheese Ball",
  "Taco Salad",
  "Thistle Shoyru Ice Cream",
  "Tomato",
  "Tooth Faerie Ice Lolly",
  "Treasure Map Negg",
  "Tuskaninny Veggieloaf",
  "Vanilla Kougra Pudding",
  "Vanilla Milkshake",
  "Vegetarian Cheeseburger",
  "Veggie Tuskabob",
  "Water Ice Cream",
  "Wocky Veggies and Dip",
  "Yurble Pasta"
];

// List Items > 1,900 - 4,000 NP
const List1 = [
  "A Smatter of Butter",
  "Acara Day Burger",
  "Acara Day Spaghetti",
  "Aisha Day Soup",
  "Baby Shoyru Baby Bottle",
  "Bacon Achyfi",
  "Bag of Nuts",
  "Banana Achyfi",
  "Banana Roll",
  "Barbecued Meat",
  "Basket of Spaghetti",
  "Berry Delight",
  "Berry Smore",
  "Bitten Red Apple",
  "Black Currant Milkshake",
  "Boiled Peanut Dash Peanuts",
  "Bori Cheese Sandwich",
  "Borovan Chicken",
  "Bottle of Water",
  "Bran Boulders",
  "Brightly Coloured Easter Negg",
  "Brightvale Rigamaroll",
  "Broccoli",
  "Broccoli Achyfi",
  "Bubbly Rhuby Fruit Juice",
  "Butter Toffee Popcorn",
  "Camouflage Hot Dog",
  "Caramel Flavoured Kougra Milk",
  "Carrot",
  "Carrot Fizz Achyfi",
  "Carrot Salad",
  "Checkered Burger",
  "Cheddar and Screlon Plate",
  "Cheddar Fries",
  "Cheery Tomato Soup Bowl",
  "Cheese and Raspberry Plate",
  "Cheese Sticks",
  "Cheesecake Salad",
  "Cheesy Kyrii Sandwich",
  "Cheesy Mashed Potato",
  "Cheesy Slorgwich",
  "Chia Chia Pudding",
  "Chiazilla Quesadilla",
  "Chicken Curry",
  "Chicken With Vegetables",
  "Chocolate Drizzled Popcorn",
  "Chocolate JubJub Sundae",
  "Chocolate Milk",
  "Chocolate Techo Cookie",
  "Chocolate Techo Foot",
  "Chocolatey Pork Chops",
  "Chokato Chomby Crisps",
  "Chomby Hot Dog",
  "Christmas Quiggle Lettuce and Tomato Wrap",
  "Cinnamon Toasties Blast",
  "Coral Delight",
  "Corn Chowder Soup Bowl",
  "Corn Horn",
  "CPMPB Sandwich",
  "Cranberry Flavoured Borovan",
  "Cranberry Fog Drink",
  "Cream Cheese Dip",
  "Cream Cheese Pretzel Bites",
  "Crimson Ham",
  "Crispy Crunchy Cookies Cereal",
  "Cucumber Salad",
  "Date Milkshake",
  "Delicious Borovan Crepe",
  "Dirt Cheese",
  "Doglefox Popcorn",
  "Dung Negg",
  "Durian Custard",
  "Durian Lupe Treat",
  "Edible Argyle Socks",
  "Edible Orange Socks",
  "Eggs Benedict",
  "Elephante Chicken Nuggets",
  "Elephante Milkshake",
  "Elephante Salad",
  "Eyrie Meatloaf",
  "Fake Blumaroo Steak",
  "Fancy Star Burger",
  "Fancy Waffles",
  "Flaming Chocolate Cake",
  "Flaming Hot Chips",
  "Flotsam Flakes",
  "Forbidden Forever Fruit",
  "Fresh Durian",
  "Fresh Green Salad",
  "Fresh Turnip Sandwich",
  "Fried Eggs and Scallion Tortillas",
  "Fruit Krawk Pot",
  "Furanga Fruit Sandwich",
  "Garlic Bread Halves",
  "Garlic Kebab",
  "Garlicy Mushrooms",
  "Gnocchi Beef Stew",
  "Gnorbu Sushi",
  "Gnorbu Wool Noodles",
  "Gold Koi Crackers",
  "Goldy Crackers",
  "Good Popcorn",
  "Gooseberry Jam Packed Lunch",
  "Grapefruit Neocola",
  "Grarrl Crackers",
  "Grarrl Macaroni",
  "Grey Cheese",
  "Grey Peach Pie",
  "Ham and Cheese Mashed Potato",
  "Honey Glazed Ham",
  "Hot Doughnutfruit Juice",
  "Illusen Lunch Box",
  "Jhudora Day Burger",
  "Jhudora Day Ice Cream",
  "Jhudora Day Pastry",
  "Jhudoras Achyfi",
  "Jicama",
  "Jinjah Maple Mocktail",
  "JubJub Orange Juice",
  "JubJub Strawberry Juice",
  "Juppie Cheese Wedge",
  "Kale",
  "Korbat Tea Sandwiches",
  "Kougra Day Burger",
  "Krawk Brand Crisps",
  "Lava Bread",
  "Lava Bread Bowl",
  "Left-Over Turkey Wing Sandwich",
  "Lemon Lime Neocola",
  "Lenny Cream of Onion Soup",
  "Limeade",
  "Lucky Slothy Day Dip",
  "Lupe Soup",
  "Lutari Pancakes",
  "Lutaya",
  "Lutical Berries",
  "Marble Cake",
  "Marshmallow Yam Soup",
  "Meat Tuskabob",
  "Meerca Cinnamon Bun",
  "Meerca Sundae",
  "Mighty Grarrl Burger",
  "Mini Cheddar Kau Cheese Wheel",
  "Mini Ice Cream",
  "Mixed Grarrl Salad",
  "Moehog Grilled Peanut Butter Sandwich",
  "Mouldy Mini Kau Cheese Wheel",
  "Mushrooms On A Stick",
  "Mutant Hot Dog",
  "Mynci Vegetable Burger",
  "Nachos With Cheese",
  "Neggnog Cheesecake",
  "Nimmo Meatloaf",
  "Noil Cracker",
  "Orange Bruce Juice",
  "Orange Flavoured Borovan",
  "Orange Lupe Treat",
  "Orange Spanner Jelly",
  "Orange Uni Sherbert Sundae",
  "Orange-Stuffed Turkey with Jam Dressing",
  "Orapple Fizz",
  "Origami Breakfast",
  "Origami Donut",
  "Paper Negg",
  "Pasta Nest",
  "Pastrami Milkshake",
  "Pat of Butter",
  "Pea and Carrot-Stuffed Turkey",
  "Pea and Ham Baby Food",
  "Peach Milkshake",
  "Peanut",
  "Peanut Butter & Jelly JubJub Sandwich",
  "Peanut Butter Bone",
  "Peanut Butter Crackers",
  "Peanut Butter Toast",
  "Peanut Dash Cookie",
  "Peanut Dash Shake",
  "Peophin Pancakes",
  "Pineapple Ham",
  "Plain Bagel",
  "Plain Onigiri",
  "Plain Shoyru Meatball",
  "Plate of Crudites",
  "Plushie Broccoli",
  "Plushie Burger",
  "Plushie Slice of Cake",
  "Plushie Turkey",
  "Popcorn",
  "Potato-Stuffed Turkey",
  "Rainbow Poogle Lolly",
  "Rainbow Toast with Rainbow Jam",
  "Rangamelon",
  "Raspberry Cranberry Juice",
  "Ruki Juicebox",
  "Sand Negg",
  "Sausage Cornucopia",
  "Sausage Jacket Potato",
  "Scorched Veggies",
  "Scrumptious Borovan Cookie",
  "Shoyru Cereal",
  "Shoyru Spaghetti",
  "Skeith Crisps",
  "Skeith Quesadilla",
  "Skeith Sundae",
  "Skull Stew",
  "Sloth Day Pasta",
  "Snowy Negg",
  "Soba Noodles",
  "Sparkling Pink New Year Juice",
  "Sparkling Space Cocktail",
  "Sparkling Twirly Fruit Juice",
  "Speckled Candy Floss",
  "Speckled Ice Cream",
  "Spicy Peophin Burger",
  "Squid Spaghetti",
  "Sroom Fruit Sandwich",
  "Starry Taco",
  "Steamed Dumplings",
  "Steel Negg",
  "Stormy Negg",
  "Strawberry Blumaroo Cone",
  "Strawberry Gelert Shake",
  "Strawberry Ice Cream Sandwich",
  "Strawberry Waffle Cone",
  "Super Icy Custard",
  "Symol Extra Cheesy Cheese Ball",
  "Tchea JubJub Mini Burger",
  "Teasicle",
  "Techo Garden Salad",
  "Tigerbuggle Jacket Potato",
  "Tigerbuggle JubJub Mini Burger",
  "Tofu Pumpkin",
  "Tofukabob",
  "Turkey Casserole",
  "Turkey Croquettes",
  "Turkey Leg",
  "Turkey Leg Pasta",
  "Turkey Wing Dinner",
  "Twirly Fruit Juice",
  "Two Garlic Bulbs",
  "Uh Oh, Spaghetti Eyes",
  "Vanilla Waffle Cone",
  "Vegan Turkey Dinner",
  "Warm Transparaberry Cocktail",
  "Water Cake",
  "White Chocolate Pear",
  "Xweetok Bologna Sandwich",
  "Xweetok Burger",
  "Yooyuball Pizza",
  "Yurble Steak",
  "Zafara Gruel"
];

// List Items 4,000 - 40,000 NP
const List2 = [
  "A Smatter of Ketchup",
  "A Smatter of Mayo",
  "A Smatter of Mustard",
  "Aisha Mega Burger",
  "Apple Achyfi",
  "Apple Flavoured Borovan",
  "Apple Rigamaroll",
  "Baby Bruce Milk Bottle",
  "Bacon Tape",
  "Banana Grub",
  "Beef and Veggie Soup",
  "Beef Wellington",
  "BeYOUtiful Burgers",
  "Black Cherry Taco",
  "BLT Sandwich with Cheese",
  "Blue Berry Aisha Ice Cream",
  "Blue Bruce Juice",
  "Blueberry and Orange Blend",
  "Blueberry Jelly Twirl",
  "Blumaroo Ice Cream Sundae",
  "Bowl Hominy",
  "Bowl of Mushy Peas",
  "Brown Sugar Oatmeal",
  "Bubbly Harffel Fruit Juice",
  "Bubbly Roseatte Juice",
  "Bubbly Twirly Fruit Juice",
  "Buzz Bread Salad",
  "Buzz Dung Cone",
  "Buzz Mashed Potato",
  "Buzz Sandwich With Honey",
  "Caesar Salad",
  "Caramel Chia Parfait",
  "Carrot Cupcake",
  "Carrot Fizz Achyfi",
  "Cheddar Kacheek Cheese",
  "Cheese and Pickle Packed Lunch",
  "Cheese Negg",
  "Cheese Rigamaroll",
  "Cheesy Kois",
  "Cheesy Onion Noodle Soup",
  "Cheesykraut Hot Dog",
  "Cherry Mynci Burger",
  "Chestnut Shortcake",
  "Chestnut Soup",
  "Chia Cereal",
  "Chicken Dumpling Soup",
  "Chicken Taquitos",
  "Chips and Egg",
  "Chocolate Aisha Sundae",
  "Chocolate Chip Gelert Ice Cream Sandwich",
  "Chocolate Chomby Ice Cream Sandwich",
  "Chocolate Covered Apple",
  "Chocolate Covered Toffee",
  "Chocolate Gnome Crunch",
  "Chocolate Kau Milk",
  "Chocolate Lupe Ice Cream",
  "Chocolate Poogle Cupcake",
  "Chocolate Poogle Lolly",
  "Chokato Cream Cheese Dip",
  "Chokato Omurice",
  "Chunky Mushroom Soup",
  "Cinnamon Apple Chips",
  "Cinnamon Neocola",
  "Cinnamon Toasties",
  "Clam and Meatball Pizza",
  "Cole Slaw",
  "Congratulations Negg",
  "Continuous Meat",
  "CPMPB Salad",
  "Cream of Tchea Soup",
  "Creamed Corn",
  "Creamy Jello Jigglers",
  "Creamy Sweet Potato Soup",
  "Crunchy Buzz Honey Delight",
  "Crusty Clam Surprise",
  "Cupcake with Rainbow Frosting",
  "Cupid Negg",
  "Curried Chicken Tea Sandwiches",
  "Cybunny Carrot Stew",
  "Cybunny Pancakes",
  "Dark Chocolate Covered Toffee",
  "Deceptive Soup",
  "Deep-Fried Candy Floss",
  "Deep-Fried Okra",
  "Deep-Fried Vegetables",
  "Deluxe Ham Sub",
  "Dipping Apples",
  "Dirt Achyfi",
  "Dirt Ice Cream",
  "Disco Ice Cream",
  "Disco Toast",
  "Doglefox Candy Floss",
  "Doglefox Cookies",
  "Double Scoop of Sorbet",
  "Double Stuffed Guppy",
  "Draik Salad",
  "Draik Soup",
  "Dressing and Cranberry Sandwich",
  "Dried Lupe Snack",
  "Dubloon Nuggets",
  "Egg Pate",
  "Egg Roll",
  "Egg Salad Packed Lunch",
  "Egg Stew",
  "Eggy Weggs",
  "Elephante Ice Cream",
  "Extra Large Fizzy Drink",
  "Extra Large Xweetok Sushi",
  "Extra Meaty Pie",
  "Extra Meaty Sandwich",
  "Fancy Rack of Lamb",
  "Felberry Gormball Sandwich",
  "Festive Faerie Fizz",
  "Fish Filet Sandwich",
  "Fizzy Apple Juice",
  "Fizzy Grape Lupe Drink",
  "Flied Rice",
  "Florg Os Cereal",
  "Flotato-Stuffed Turkey",
  "Flowers and Coffee",
  "Freeze Dried Bacon",
  "Freeze Dried Meat",
  "French Toast",
  "Fresh Borovan and Asparagus Tart",
  "Fried Potato Balls",
  "Fruit Punch Roll",
  "Fruity Aisha Sundae",
  "Garlic Mashed Potatoes",
  "Giblets Gravy",
  "Gingerbread Cookie Box",
  "Glass of Water",
  "Gnorbu Chocolate Pudding",
  "Gnorbu Wool Burger",
  "Gnorbu Wool Candy Floss",
  "Golden Tangerines",
  "Good Popcorn",
  "Gooey Green Shake",
  "Gourmet Fried Chicken and Waffles",
  "Gourmet Grilled Steak Salad",
  "Granola Parfait",
  "Grape Juice Sippy Cup",
  "Grapeade",
  "Grapefruit Biscuits",
  "Green Scorchipepper",
  "Grey Ice Cream",
  "Grilled Cheese Soup Dippers",
  "Grilled Islandberry Slices",
  "Gummy Dice Salad",
  "Hairy Fungus Salad",
  "Ham and Mustard Packed Lunch",
  "Ham Casserole",
  "Happy Birthday Negg",
  "Harvest Soup Bowl",
  "Hash Browns",
  "Hearty Pie",
  "Honeydew Melon",
  "Hot Buzz Pie",
  "Hot Fruit Soup",
  "Hot Fudge Sundae",
  "Hot Meerca Tea",
  "Iced Shoyru Meatball",
  "Invisible Negg",
  "Ixi Acorn Meatball",
  "Ixi Double Veggie Burger",
  "Jelly Neocola",
  "Jhudora Eyeball Pasta",
  "Jinjah Ale",
  "JubJub Strawberry Juice",
  "Kacheek Meatball",
  "Kadoatie Puffs",
  "Knowledge Hungry Burger",
  "Koi Seaweed Sundae",
  "Korbat Cheese and Crackers",
  "Korbat Veggie Plate",
  "Kyrii Dewy Apple Milkshake",
  "Kyrii Florange Milkshake",
  "Left-Over Sliced Turkey Sandwich",
  "Lemon",
  "Lemon and Orange Blend",
  "Lettuce Wrap",
  "Liver Poogle Pate",
  "Lupe Burger",
  "Mayonnaise Chilli and Cheese covered Corn on the Cob",
  "Meaty Gnorbu Pie",
  "Meerca Bolognese",
  "Meridellian Chocolate Milk Glass",
  "Mini Koi Cereal",
  "Mint Chip Skeith Cone",
  "Minty Aisha Sundae",
  "Moehog Fruit Leather",
  "Moehog Milkshake",
  "Morel Mushroom Dip",
  "Mosaic Negg",
  "Mouldy Mini Kau Cheese Wheel",
  "Mutant Doughnut",
  "Mutant Kau Milkshake",
  "Mutant Toast",
  "Mynci Fruit Kebab",
  "Negg",
  "Negg Noodle Soup",
  "Neggdrop Soup",
  "Nimmo Day Fruit Cake",
  "Noil Mashed Potatoes",
  "Number Crackers and Cheese",
  "Number Fruit Leather",
  "Number Jelly Parfait",
  "Number Pasta",
  "Nutty Spaghetti",
  "Oatmeal Raisins",
  "Ogrin Pasta",
  "Ogrin Peanut Butter and Jelly Sandwich",
  "Orange Baby Aisha Lollypop",
  "Orange Jetsam Cupcake",
  "Orange Juice",
  "Orange Roll",
  "Orange Yurblecone",
  "Oyster Obsession",
  "Paper-Wrapped Chicken",
  "Paper-Wrapped Salmon",
  "Paper-Wrapped Veggies",
  "Pastrami Gormball Sandwich",
  "Peanut Butter & Jelly Waffle Sandwich",
  "Peanut Butter and Jelly Gormball Sandwich",
  "Peanut Butter and Jelly Hot Dog",
  "Peanut Butter Smores",
  "Peanut Butter Tonu Crackers",
  "Pickled Apples",
  "Pickled Onion",
  "Pineapple and Broccoli Pie",
  "Pink Cheese",
  "Pink Triple Decker Sandwich",
  "Plain Crackers",
  "Poogle Pot Pie",
  "Portobello Platter",
  "Potato Salad",
  "Quadruple Scoop of Sorbet",
  "Rainbow Poogle Lolly",
  "Raspberry Basket",
  "Raspberry Scones",
  "Raspberry Sundae",
  "Raspberry Yurblecone",
  "Red Bruce Juice",
  "Red Buzz Energy Drink",
  "Red Scorchipepper",
  "Refried Beans and Rice",
  "Roast Chestnut Neggnog",
  "Royal Girl Zafara Pancakes",
  "Salmon Cream Cheese Dip",
  "Sausage and Chips",
  "Sausage Gravy",
  "Scorched Kabob",
  "Scorchio Smores",
  "Seasoned Curly Chips",
  "Seaweed Bacon",
  "Shell Lollypop",
  "Shiver Me Shrimp",
  "Sketch Eggs",
  "Sketch Pie",
  "Sketch Sandwich",
  "Sketch Sundae",
  "Skull-n-Bones Pasta",
  "Slice of Zafara Pizza",
  "Slorg Biscuits",
  "Small Fizzy Drink",
  "Smiley Pancakes",
  "Snorkle in a Blanket",
  "Snot Fries",
  "Snot Sandwich",
  "Snotty Vira Onion",
  "Snow Enchiladas",
  "Snow Lemon",
  "Sour Apple Ixi Fizzy Drink",
  "Sour Cream Chomby Crisps",
  "Spaghetti Hot Dog",
  "Sparkling Blue New Year Juice",
  "Speckled Veggie Burger",
  "Spicy BBQ Chomby Crisps",
  "Spicy Kau Burger",
  "Spicy Purblare Juice",
  "Spinach Alfredo Omurice",
  "Spotted Kau Sandwich",
  "Sprinkling of Salt",
  "Squid Sauce",
  "Star Shaped Cheeseburger",
  "Starflower Patterned Easter Negg",
  "Steak Platter",
  "Stone Veggie Gormball Sandwich",
  "Strawberry Achyfi",
  "Strawberry Cybunny Ice Cream",
  "Strawberry Ixi Fizzy Drink",
  "Strawberry Jetsam Ice Cream",
  "Strawberry Oatmeal",
  "Strawberry Parfait",
  "Strawberry Scorchio Treat",
  "Strawberry Skeith Cone",
  "Stuffed Chokatos",
  "Sweet and Sour Soup",
  "Swirly Chocolate Milk",
  "Symol Mouldy Cheese Ball",
  "Tall Stack of Mutant Pancakes",
  "Techo Foot Sandwich",
  "Terror Mountain Chocolate Milk Glass",
  "Thing Rolls",
  "Thistleberry Sandwich",
  "Tigerbuggle JubJub Mini Burger",
  "Tofu Poogle Pate",
  "Tomato Cannon Ball",
  "Tomato Omurice",
  "Tropical Breeze",
  "Turkey Curry",
  "Turkey Dinner",
  "Turkey Dumplings",
  "Turkey Enchilada",
  "Turnip Eyrie Souffle",
  "Tuskaninny Ice Cream",
  "Twirly Fruit Cream Cheese Dip",
  "Twirly Fruit Shoyru Ice Cream",
  "Uni Corn",
  "Uni Crisps",
  "Unripe Puntec Wrap",
  "Valentines Day Strawberry Bouquet",
  "Valentines Negg",
  "Vanilla Gnorbu Cupcake",
  "Vanilla Neocola",
  "Vanilla Skeith Cone",
  "Vanilla Yurblecone",
  "Veal Parmesan Gormball Sandwich",
  "Vegetarian Usul Wrap",
  "Veggie Delight Jetsam Fin Crackers",
  "Veggie Poogle Pate",
  "Waffle Burger",
  "White Chocolate Asparagus Souffle",
  "White Chocolate Covered Toffee",
  "Wishbone Delight",
  "Wocky Spaghetti Ball",
  "Wormy Jam Sandwich",
  "Xweetok Sugar Cookies",
  "Xweetok Vegetable Soup",
  "Yamless Candied Yams",
  "Yurble Pot Pie",
  "Zafara Breakfast",
  "Zafara Hot Chocolate",
  "Zafara Veggie Stew",
];

// List Items 40k - 500k NP
const List3 = [
  "A Dozen Neggs",
  "Acara Rainbow Lollypop",
  "Aisha Tomato and Potato Soup",
  "Apple Juice Sippy Cup",
  "Apple Walnut Tea Sandwiches",
  "Asparagus Borovan Lasagne",
  "Baby Elephante Milk Bottle",
  "Bacon Taco",
  "Baked Avocado with Curried Sauce",
  "Baked Juppie",
  "Battle Duck Negg",
  "Black Cherry Ice Lolly",
  "Blackberry Sorbet",
  "Blue Acara Cake",
  "Blue Negg",
  "Blueberry Jelly Doughnut",
  "Bombshroom",
  "Bori Bowl of Fruit",
  "Borovan Brownies",
  "Borovan Cookies",
  "Borovan Layered Cake",
  "Breakfast Cake",
  "Buzz Honey Pot",
  "Buzz Sandwich",
  "Candy Cane Negg",
  "Caramel Coated Pear",
  "Carrots in Salad",
  "Checkered Carrot",
  "Cheese and Tonu Crackers",
  "Cheesy Choco Cookie",
  "Cherimoya",
  "Chocolate Coated Pear",
  "Chocolate Covered Carrot",
  "Chocolate Covered Tomato",
  "Chocolate Elephante Doughnut",
  "Chocolate Ice Cream",
  "Chocolate Nimmo Dessert",
  "Chocolate Shoyru Meatball",
  "Chokato Neggnog",
  "Chokato Sundae",
  "Chokato Toffee Apple",
  "Chomby Juice",
  "Christmas Pattern Negg",
  "Christmas Wocky Cranberry Meatloaf",
  "Cookie Negg",
  "Custard",
  "Custard Cheesecake",
  "Decorative Negg",
  "Deep-Fried Mac-n-Cheese Loaf",
  "Deluxe Cheese Fondue",
  "Deluxe Elephante Cake",
  "Deluxe Peophin Burger",
  "Diet Big Gulp Neocola",
  "Doglefox Ice Cream Scoops",
  "Dorkleshroom",
  "Doughnutfruit Punch",
  "Draik Wrap",
  "Egg and Carrots",
  "Evil Popcorn",
  "Exotic Plant",
  "Exotic Sliced Truffles",
  "Extra Fancy Crackers",
  "Fall Leaf Salad",
  "Fire Carrot",
  "Fire Tonic",
  "Flaming Hot Burger",
  "Flotsam Fin Soup",
  "Flotsam Ice Cream Sundae",
  "Flower Nectar",
  "French Toast PB&J Sandwich",
  "Fried Negg Sandwich",
  "Fried Something Something",
  "Frozen Veggie Delight",
  "Fruit Basket",
  "Fruit Tart",
  "Glass Negg",
  "Gnome Crunch",
  "Green Negg",
  "Grey Toast",
  "Grootafruit Punch",
  "Hot Dog on a Stick",
  "Illusen Negg",
  "Jalapeno Kacheek Cheese",
  "Jetsam Seafood Soup",
  "JubJub Coconut Juice",
  "Kau Waffles",
  "Korbat Pasta and Meatballs",
  "Kyrii Agueena Milkshake",
  "Kyrii Jumbleberry Milkshake",
  "Lamb Chop",
  "Lemon Lava Cake",
  "Lemon Swirly Negg",
  "Lime Swirly Negg",
  "Lutari Fizz",
  "Maple Syrup Negg",
  "Mega Manoroot Sandwich",
  "Mild Cheddar Jetsam Fin Crackers",
  "Mini Kau Cheese Wheel",
  "Mini Swiss Kau Cheese Wheel",
  "Mynci Surprise Ice Cream",
  "Neopets 18th Birthday Cake",
  "Neopia Central Chocolate Milk Glass",
  "Noil Candy Floss",
  "Orange Baby Aisha Lollypop",
  "Orange Negg",
  "Ornate Purple Negg",
  "Partitioned Negg",
  "Peanut Dash Stir Fry",
  "Peppered Salmon Dish",
  "Petpet Crackers",
  "Pickled Pears",
  "Pickled Peppers",
  "Pineapple and Oranges",
  "Pink Negg",
  "Pirate Pancakes",
  "Pizza Sandwich",
  "Pomegranate",
  "Pumpkin Bread",
  "Purple Cybunny Negg",
  "Purple Eyrie Jelly Sandwich",
  "Purple Hamburger",
  "Purple Negg",
  "Puzzle Fruit",
  "Quiggle Veggie Soup",
  "Rainbow Neggnog",
  "Raspberry Aisha Waffle",
  "Raspberry Baby JubJub Lollypop",
  "Rock Negg",
  "Ruki Salad",
  "Scaled Negg",
  "Seasoned Lupe Chips",
  "Shenkuu Chocolate Milk Glass",
  "Sloth Day Nachos",
  "Sloth Day Soup",
  "Space Station Chocolate Milk Glass",
  "Speckled Negg",
  "Spotted Kau Ice Cream",
  "Square Marshmallows",
  "Squibble Berry Sandwich",
  "Starfish Cake",
  "Steak Negg",
  "Strawberry Taco",
  "Super Icy Negg",
  "Super Spicy Borovan",
  "Suspicious Borovan Creame Pie",
  "Sweet and Sour Negg",
  "Swirly Negg #498",
  "Symol Cheddar Cheese Ball",
  "Tarragon Achyfi",
  "Tasty Guacamole",
  "Tea Biscuits",
  "Tea Waffles",
  "Techo Jelly Surprise",
  "Thick Chocolate Soup",
  "Thorn on the Cob",
  "Thornberry Bagel",
  "Toast",
  "Toffee Chocolate Aisha Sundae",
  "Tomato Baby Food",
  "Tonu Cheeseburger",
  "Tonu Orange Juice",
  "Tonu Sorbet",
  "Tonu Tonic Water",
  "Turkey Drumstick Dinner",
  "Twin Salad",
  "Ultimate Icy Negg",
  "Ultra Icy Negg",
  "Uni Crisps",
  "Uni Ice Cream",
  "Vanilla Blumaroo Cone",
  "Vanilla Flavoured Borovan",
  "Vanilla Gelert Ice Cream Sandwich",
  "Vanilla JubJub Sundae",
  "Vanilla Poogle Cupcake",
  "Watercress Tea Sandwiches",
  "Watermelon Jetsam",
  "Watermelon Maraquan Shoyru",
  "Watermelon Roll",
  "Welsh Rarebit",
  "White Cheddar Jetsam Fin Crackers",
  "Whole Wheat Jetsam Fin Crackers",
  "Wintermelon",
  "Wocky Plum Pudding",
  "Yellow Negg",
];

// List Items > 40,000 NP +
const List4 = [
  "Acara Ice Cream Surprise",
  "Assorted Vandagyre Approved Nuts",
  "Baby Bloater",
  "Bag of Peanuts",
  "Bangers and Mash",
  "Barnacle Bills Belt Busting Burger",
  "Berry Joy Fun Pop",
  "Big Gulp Neocola",
  "Bilge Rat Madeira",
  "Black Caviar",
  "Black Currant Juice",
  "BLT Croissant",
  "Blue Cybunny Negg",
  "Blue Picnic Hamper",
  "Blueberry and Oyster Ice Cream",
  "Bomberry Grog",
  "Borovan Hot Chocolate Bomb",
  "Borovan Pavlova",
  "Candy Floss Carrot",
  "Cannon Fodder",
  "Capn Threelegs Cutlass Crusade",
  "Carrot Crown",
  "Chain of Onions",
  "Cheesy Carrot Chunks",
  "Cheesy Chocoshake",
  "Cheesy Chokato Pie",
  "Cheesy Krawk Dip",
  "Cheesy Strawberry Slice",
  "Cherry Pop",
  "Chocolate Coated Blue Cheese",
  "Chocolate Coated Cheese",
  "Chocolate Coated Cheese Strings",
  "Chocolate Coated Holey Cheese",
  "Chocolate Covered Carrot",
  "Chocolate Green Tea Parfait",
  "Chocolate Joy Fun Pop",
  "Chokato Rigamaroll",
  "Container of Purple Liquid",
  "Cucumber Tea Sandwiches",
  "Cybunny Day Canape",
  "Donut Burger",
  "Egg and Tomato Sandwich",
  "ErgyFruit Grog",
  "Fancy Rack of Lamb with Fruit",
  "Fire Apple",
  "Fire Fondue",
  "Flaming Tuskaninny Ice Cream",
  "Forbidden Plunder",
  "Fun Icy Cheese Pop",
  "Funnydew Neggnog",
  "Glowing Apple",
  "Golden Caviar",
  "Grape Pop",
  "Green Ham",
  "Green Picnic Hamper",
  "Grey Juice",
  "Grog Light",
  "Happy Anniversary Negg",
  "Harffel Flavoured Milk",
  "Headless Horsefish",
  "Heart Shaped Negg",
  "Hogshead",
  "Honey and Bacon Burger",
  "Ice Apple",
  "Illusens Family Recipe Cake",
  "Invisible Cookie",
  "Island Meatloaf",
  "Kadoatie Biscuits",
  "Kau Kau Farm Organic Bottled Milk",
  "Kau Kau Farm Soy Milk",
  "Keel Haul",
  "Krakuberry Cove",
  "Krakuberry Grog",
  "Land Lubber",
  "Lawyerbot Degreaser",
  "Le Sausage",
  "Leftover Shortcrust Pastry",
  "Lemon Pop",
  "Lemonade",
  "Lenny Salad",
  "Loretta Fontaines Perfect Pizza",
  "Man O War",
  "Meerca Apertif",
  "Mega Pipper Sandwich",
  "Mega Sandwich",
  "Mega Tuna Sandwich",
  "Mocha Joy Fun Pop",
  "Mutated Negg",
  "Olivetato",
  "Onion and Mustard Pie",
  "Our Famous Krawk Pie",
  "Peach Jelly",
  "Phear Flavoured Milk",
  "Pinanna Paradise",
  "Pirate Negg",
  "Plum",
  "Polka Carrot",
  "Pretty Purple Princess Negg",
  "Puntec Cupcake",
  "Puntec Parcel",
  "Purple Picnic Hamper",
  "Purple Potato Aperitif",
  "Rainbow Apple",
  "Rainbow Carrot",
  "Rainbow Cybunny Negg",
  "Rainbow Negg",
  "Raspberry Pop",
  "Raspberry Toffee Apple",
  "Red Picnic Hamper",
  "Seaweed Flotsam Burger",
  "Slithering Squid Surprise",
  "Square Meat",
  "Squid on a Stick",
  "Starry Cupcake",
  "Starry Scorchipepper",
  "Steak Surprise",
  "Sugar Coated Apple Fritters",
  "Suti Jam Triple Decker",
  "Tchea Grog",
  "Tchea Toasty",
  "Tchea Toffee Apple",
  "Tea Infuser",
  "Tea Jelly",
  "Techo Energy Drink",
  "Thornberry Gormball Sandwich",
  "Tigersquash Custard",
  "Toast on Toast",
  "Twirly Fruit Flavoured Milk",
  "Twirly Fruit Toasty",
  "Uni Pie",
  "Uni Salad",
  "Uni Triple Scoop Rainbow Sorbet",
  "Upside Down Ice Cream",
  "Vanilla Aisha Pudding",
  "Vanilla Flotsam Day Shake",
  "Walk The Plank",
  "Wheaty Kyrii Sandwich",
  "Wocky Steak",
  "Xweetok Hot Chocolate",
  "Xweetok Veggie Crepe",
  "Zeenana Toffee Apple",
];

// Function to apply styles to items based on the current array
(function() {
    'use strict';
    // Display a Key on page
    // Create the price key div element
    var keyDiv = document.createElement('div');

    // Set styles to make it subtle and fixed to the right side
    keyDiv.style.position = 'fixed';
    keyDiv.style.top = '180px';
    keyDiv.style.right = '3px';
    keyDiv.style.backgroundColor = 'rgba(255, 255, 255, 0.9)';
    keyDiv.style.border = '1px solid #ccc';
    keyDiv.style.padding = '10px';
    keyDiv.style.fontSize = '11px';
    keyDiv.style.fontFamily = 'Arial, sans-serif';
    keyDiv.style.zIndex = '1000';
    keyDiv.style.width = '90px';
    keyDiv.style.maxHeight = '90vh'; // Ensures it doesn't overflow the viewport
    keyDiv.style.overflowY = 'auto'; // Scroll if needed
    keyDiv.style.opacity = '0.4'; // Make it more subtle
    keyDiv.style.transition = 'opacity 0.2s';

    // Hover effect to make it more visible when hovered over
    keyDiv.onmouseover = function() {
        keyDiv.style.opacity = '1';
    };
    keyDiv.onmouseout = function() {
        keyDiv.style.opacity = '0.6';
    };

    // The content of the key with added space and alignment tweaks
    keyDiv.innerHTML = `
    <div style="display: flex; align-items: center;">
    <strong>- Price Key -</strong></center><br><br>
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; background-color: #f1f1f1; margin-right: 5px;"></div>
        < 700 np
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; background-color: #fff; margin-right: 5px;"></div>
        700 - 1,900
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; border: 1px dotted green; margin-right: 5px;"></div>
        1,900 - 4,000
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; border: 1px solid orange; margin-right: 5px;"></div>
        4,000 - 40k
    </div>
    <div style="display: flex; align-items: center;">
        <div style="width: 12px; height: 12px; border: 2px dashed red; margin-right: 5px;"></div>
        40k - 500k
    </div>
    <div style="display: flex; align-items: center;">
        <div style="width: 12px; height: 12px; border: 2px solid red; margin-right: 5px; margin-top: 5px;"></div>
        500k +
    </div>
`;

    // Append the price key div to the body
    document.body.appendChild(keyDiv);
})();

// Function to apply styles to items based on the current array
function applyStylesToItems(itemArray) {
  var itemNames = document.getElementsByClassName("item-name");

  for (var i = 0; i < itemNames.length; i++) {
    var itemName = itemNames[i].textContent.trim();

    if (itemArray.includes(itemName)) {
      // Apply different styles based on the array order
      if (itemArray === List4) {
        // Red Thick Box
        notificationSound.play(); // Play sound
        itemNames[i].parentNode.style.border = "5px solid red";
        itemNames[i].parentNode.style.padding = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 0, 0, 0.2)";
        itemNames[i].style.color = "red";
        itemNames[i].style.fontWeight = "800";
        itemNames[i].style.textDecoration = "underline";
      } else if (itemArray === List3) {
        // Red Dashed
        notificationSound.play(); // Play sound
        itemNames[i].parentNode.style.border = "2px dashed red";
        itemNames[i].style.color = "red";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 0, 0, 0.1)";
      } else if (itemArray === List2) {
        // Orange
        itemNames[i].style.color = "orange";
        itemNames[i].parentNode.style.border = "2px solid orange";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 165, 0, 0.2)";
      } else if (itemArray === List1) {
        // Green Dotted
        itemNames[i].style.color = "green";
        itemNames[i].parentNode.style.border = "1px dotted green";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(0, 255, 0, 0.2)";
      } else if (itemArray === List0) {
        // Light Grey
        itemNames[i].style.color = "lightgrey";
        itemNames[i].style.fontWeight = "200";
        itemNames[i].parentNode.style.paddingTop = "5px";
        var itemImgDiv = itemNames[i].parentNode.querySelector(".item-img");
        if (itemImgDiv) {
          itemImgDiv.style.opacity = "0.2";
        }
      }
    }
  }
}

// Loop through each price array and apply styles
applyStylesToItems(List4);
applyStylesToItems(List3);
applyStylesToItems(List2);
applyStylesToItems(List1);
applyStylesToItems(List0);