// ==UserScript==
// @name         [obj 01] Fresh Foods
// @version      1.7
// @description  Highlights items, price key, added sound & refresh
// @namespace    https://github.com/uxillary/neo-qol
// @author       adamski @uxillary
// @match        https://www.neopets.com/objects.phtml?obj_type=1&type=shop
// @icon         https://www.google.com/s2/favicons?sz=64&domain=neopets.com
// @grant        none
// ==/UserScript==

const refreshKey = 'refreshEnabled01'; // Key to track refresh state in localStorage
const minRefreshTime = 9001; // Minimum refresh interval (5 seconds)
const maxRefreshTime = 16601; // Maximum refresh interval (12 seconds)

// Load notification sound
const notificationSound = new Audio("https://raw.githubusercontent.com/uxillary/neo-qol/main/audio/bell-drop.wav");
notificationSound.volume = 0.8;

// Function to start or stop the refresh timer
function toggleRefresh() {
    const refreshEnabled = JSON.parse(localStorage.getItem(refreshKey)) || false;
    if (refreshEnabled) {
        localStorage.setItem(refreshKey, false);
        clearTimeout(refreshTimeout); // Stop refreshing
        refreshButton.textContent = "Start";
        refreshButton.style.backgroundColor = '#007BFF'; // Set button to blue when inactive
    } else {
        localStorage.setItem(refreshKey, true);
        setRandomRefresh(); // Start refreshing
        refreshButton.textContent = "Stop";
        refreshButton.style.backgroundColor = '#28a745'; // Set button to green when active
    }
}

// Function to set a random refresh interval
function setRandomRefresh() {
    if (JSON.parse(localStorage.getItem(refreshKey))) {
        const refreshInterval = Math.floor(Math.random() * (maxRefreshTime - minRefreshTime + 1)) + minRefreshTime;
        refreshTimeout = setTimeout(() => {
            location.reload();
        }, refreshInterval);
    }
}

// Create the refresh toggle button
const refreshButton = document.createElement('button');
refreshButton.style.position = 'fixed';
refreshButton.style.top = '110px';
refreshButton.style.right = '35px';
refreshButton.style.backgroundColor = JSON.parse(localStorage.getItem(refreshKey)) ? '#28a745' : '#007BFF'; // Green if active, blue if inactive
refreshButton.style.color = 'white';
refreshButton.style.padding = '8px 12px';
refreshButton.style.border = 'none';
refreshButton.style.borderRadius = '4px';
refreshButton.style.cursor = 'pointer';
refreshButton.style.fontSize = '12px';
refreshButton.style.zIndex = '1000';
refreshButton.textContent = JSON.parse(localStorage.getItem(refreshKey)) ? "Stop" : "Start";

// Add button click event to toggle the refresh
refreshButton.addEventListener('click', toggleRefresh);
document.body.appendChild(refreshButton);

// Start the refresh timer if enabled
if (JSON.parse(localStorage.getItem(refreshKey))) {
    setRandomRefresh();
}

//change list items here

// List Items < 1,000 np
const List0 = [
  "Haunted Woods Chocolate Milk Glass",
  "JubJub Blueberry Juice",
  "Open Top Onion Sandwich",
  "Vegetarian Kyrii Sandwich",
  "Aisha Hot Chocolate",
  "Delicious Custard Brulee",
  "Fresh Lemint Juice",
  "Fruity Fondue",
  "Grarrl Breakfast Platter",
  "Honey Topped Buzz Sundae",
  "Jumbo Pea Sandwich",
  "Mynci Steak",
  "Pteri Sundae",
  "Quadruple Fudge Cheese Wedge",
  "Thistleberry Tuskaninny Ice Cream",
  "Baked Chomby Crisps",
  "Bubble Negg",
  "Grilled Doughnutfruit",
  "Lemint Custard",
  "Meatless Meatballs",
  "Seared Tuna Steak",
  "Spicy Wings",
  "Strawberry JubJub Sundae",
  "Buttery Chomby Waffles",
  "Celery Salad",
  "Lime Yurblecone",
  "Turkey Steak Dinner",
  "Azzle Onigiri",
  "Cheery Tomatoes",
  "Cheesy Kyrii Sandwich",
  "Chocolate and Asparagus Achyfi",
  "Chocolate Chip Zafara Cookie",
  "Florg Nachos",
  "Gamaberry Stuffed Jacket Potato",
  "Gnorbu Burger",
  "Ham",
  "Peach Ice Cream",
  "Quiggle Foot Wrap",
  "Sliced Turkey Breast",
  "Toffee Ice Cream",
  "Clown Chia Zeenana Ice Cream",
  "Moehog Fruit Leather",
  "Scorchio Ham Sandwich",
  "Chocolate Deluxe Flotsam Day Shake",
  "Kau Kau Farm Cheese Wedge",
  "Nimmo Day Sandwich",
  "Seaweed Bacon Jacket Potato",
  "Strawberry Ice Cream",
  "Asparagus and Hollandaise Sauce",
  "Omelette with Cream Sauce",
  "Red Apple",
  "Pteri Kabob",
  "Bagel and Egg Sandwich",
  "Blended Pipper",
  "Checkered Steak",
  "Chocolate Skeith Cone",
  "Fruit Tuskabob",
  "Iced Borovan",
  "Kau Kau Farm Cheddar Cheese Brick",
  "Krawk Apple Cake",
  "Lenny Veggie Burger",
  "Meaty Usul Wrap",
  "Mutant Apple",
  "Pirate Potato Crisps",
  "Pumpkin Eyrie Souffle",
  "Sausage and Cheese Roll",
  "Scorchio Banana Cake",
  "Shoyru Parfait",
  "Tiger Shoyru Ice Cream",
  "Dried Gruel Capsules",
  "Orange Ixi Drink",
  "Shark Sandwich",
  "Water Burger",
  "Gooseberry Tuskaninny Ice Cream",
  "Lime Sorbet",
  "Orange Juice",
  "Seaweed Wrapped Cake",
  "Sketch Loaf",
  "Carrot",
  "Florg Ice Cream",
  "Meaty Pot Pie",
  "Neo Taco",
  "Real Cheese Cheesecake",
  "Grarrl Cheese Slices",
  "Mini Ice Cream",
  "Plain Negg Neggnog",
  "Krawk Apple",
  "Mango",
  "Cherry Carrot Ice Cream",
  "Tuna Sub",
  "Straw Cubes",
  "Tofu Bone",
  "Berry Xweetok Ice Cream",
  "Blackberry Elephante Sundae",
  "Flaming Hot Banana",
  "Potato Chips on a Paper Plate",
  "Shoyru Breakfast",
  "Tangy Twirly Fruit Soup",
  "Vegetarian Tonu Day Burger",
  "What the Aisha Dragged In",
  "Jalapeno Pretzel",
  "JubJub Orange Juice",
  "Scorchio Chocolate Cake",
  "Crunchy Quiggles",
  "Plain Omurice",
  "Ruki Veggie Sandwich",
  "Buttered Popcorn",
  "Dung Ice Cream",
  "Onion Bagel",
  "Rice Dice",
  "Cheesy Krawk Pot",
  "Deep-Fried Fried Fishsticks",
  "Mynci Delight",
  "Tangy Peophin Burger",
  "Veggie Poogle Wrap",
  "Extra Crispy Bacon Gum",
  "Eyrie Pancake",
  "Kyrii Chocolate Milkshake",
  "Marshmallow Milkshake",
  "Shrimp Spaghetti",
  "Sketch Cheese",
  "Cheesy Popcorn",
  "Cherry Milkshake",
  "Durian Biscuit",
  "Enoki-n-Cheese Plank",
  "Grape Roll",
  "Kau Kau Farm Half And Half",
  "Shishkafruit Jam",
  "Sketch Roast Chicken",
  "Juicee",
  "Strawberry and Lime Achyfi",
  "Chocolate Covered Strawberries",
  "Fried Shrimp",
  "Sausage on Toast",
  "Blue Goo Techo Cake",
  "Breakfast Croissant",
  "Mega Tonu Day Burger",
  "Wocky Veggies and Dip",
  "Lussion Fruit",
  "Fortune Cookie",
  "Plain Cheesicle",
  "Blueberry Crescent Lolly",
  "Carrot Cone",
  "Rose Petal Crisps",
  "Thistle Shoyru Ice Cream",
  "Sea Cocktail",
  "Fajita Chips",
  "Gruel Pizza",
  "Bitten Red Apple",
  "Cherries",
  "Elderberry Achyfi",
  "Fried Something",
  "Mac and Cheese",
  "Neocrunch Cereal",
  "Purple Carrot",
  "Rainbow Burger with Cheese",
  "Snot Wrap",
  "Tomato",
  "Tuskaninny Veggieloaf",
  "Coffee",
  "Shadow Usul Lunch Box",
  "Orange",
  "Sprinkling of Chilli Pepper",
  "Strawberry Kougra Pudding",
  "Aisha Toffee Apple",
  "Orange Bruce Juice",
  "Bitten Green Apple",
  "Apple Juice",
  "Beefy Broccoli",
  "Crunchy Kacheek Cereal",
  "Mynci Ham and Cheese Sandwich",
  "Spicy Chicken Burrito",
  "Carrot Lupe Treat",
  "Radish",
  "Bacon Muffin",
  "Green Grapes",
  "Custard Parfait",
  "Funky Carrot",
  "Mint Ice Cream",
  "Yurble Pasta",
  "Coco NeoCrunch",
  "Cheeseburger",
  "Chokato Kougra Pudding",
  "Coffee Milkshake",
  "Extra Sour Seedless Skeem Jam",
  "Green Cabbage",
  "Molten Hot Chilli",
  "Sushi Rolls",
  "Cheesy Meat Wrap",
  "Gruel Ice Lolly",
  "Chocolate Milkshake",
  "Mynci Mushroom Soup",
  "Dried Chilli Peppers",
  "Can of Neocola",
  "Deli Turkey Slices",
  "Cheese Tortilla",
  "Endless Salad and Bread Sticks",
  "Green Apple",
  "Teasicle",
  "Vanilla Milkshake",
  "Banana Milkshake",
  "Borovan Ice Cream Scoop",
  "Cawl",
  "Chilli Salmon Souffle",
  "Chokato Crisps",
  "Fried Chicken Breast",
  "Green Oat Cereal",
  "Jetsam Jam",
  "Vegetarian Cheeseburger",
  "Churros",
  "Giant Chocolette",
  "Berry Eyrie Souffle",
  "Pegleg Chicken",
  "Flaming BBQ Crisps",
  "Chocolate Coated Tangy Cheese",
  "Diet Neocola",
  "Gruel Cake",
  "Meat Wrap",
  "Crispies",
  "Buried Treasure Crackers",
  "Caramel Acara On A Stick",
  "Lemon Meringue Baby Food",
  "Bag of Chips",
  "Forest Fruit Baby Food",
  "Pack o Pumpkin Seeds",
  "Square Gelatin",
  "Water Ice Cream",
  "Chocopie Slice",
  "Raspberry Jam",
  "B-B-Q Pork",
  "Beef and Veg Baby Food",
  "Aisha Cheeseburger",
  "Cherry Twist Lollypop",
  "Strawberries and Cream Baby Food",
  "Symol White Cheddar Cheese Ball",
  "Aisha Riceball",
  "Fish and Chips",
  "Hasee Puff Cereal",
  "Neo Crackers",
  "Lupe Snack Pack",
  "Blue Cheese Draik Head",
  "Egg Salad and Cheese Sandwich",
  "Garlic Cheese Toast",
  "Orange Chicken",
  "Fried Chicken and Waffles",
  "Crab Spaghetti",
  "Mashed Potato With Gravy",
  "Pteri Wrap",
  "Corn Bread",
  "Blueberry Jetsam Jelly",
  "Jhudora Rotten Negg",
  "Acara Day Pancakes",
  "Beetroot and Cream Smores",
  "Bubbling Blue Soup",
  "Buttered Toast",
  "Dirt Pie",
  "Gummy Pirate Candies",
  "Beetroot Ice Cream",
  "Starry Crunch",
  "Taco Salad",
  "Edible Smelly Gym Socks",
  "Neggy Custard Pie",
  "Treasure Map Negg",
  "Dried Squid on a Stick",
  "Starry Cookie Pile",
  "Caviar Sandwich",
  "Chocolate Kougra Pudding",
  "Animal-style Chips",
  "Burrito in the Wall",
  "Chicken Filets with Fancy Sauce",
  "Chocolate Coated Cheese Strings",
  "Chocolate Sandwich",
  "Chocolately Cheese Wedges",
  "Egg and Tomato Basil",
  "Fish Negg Stew",
  "Leaf Taco",
  "Lime Negg",
  "Mighty Steakwich",
];

// List Items > 2k - 5k np
const List1 = [
  "Apple Achyfi",
  "Brightly Coloured Easter Negg",
  "Carrot Cupcake",
  "Draik Wrap",
  "Egg Roll",
  "Purple Eyrie Jelly Sandwich",
  "Red Bruce Juice",
  "Speckled Veggie Burger",
  "Strawberry Skeith Cone",
  "Creamy Sweet Potato Soup",
  "White Chocolate Asparagus Souffle",
  "Gummy Dice Salad",
  "Mini Kau Cheese Wheel",
  "Turkey Enchilada",
  "Glass of Water",
  "Checkered Carrot",
  "Pickled Apples",
  "Snorkle in a Blanket",
  "Valentines Day Strawberry Bouquet",
  "Royal Girl Zafara Pancakes",
  "BeYOUtiful Burgers",
  "Harvest Soup Bowl",
  "Jelly Negg",
  "Neggnog Cheesecake",
  "Nutty Spaghetti",
  "Veggie Delight Jetsam Fin Crackers",
  "Apple Flavoured Borovan",
  "Borovan Cookies",
  "Skull-n-Bones Pasta",
  "Spicy BBQ Chomby Crisps",
  "Flotato-Stuffed Turkey",
  "Sparkling Blue New Year Juice",
  "Carrot Fizz Achyfi",
  "Chokato Cream Cheese Dip",
  "Good Popcorn",
  "Portobello Platter",
  "Rainbow Poogle Lolly",
  "Tigerbuggle JubJub Mini Burger",
  "Starry Taco",
  "Bacon Achyfi",
  "Plain Onigiri",
  "Xweetok Bologna Sandwich",
  "Ice Cream Covered Jacket Potato",
  "Strawberry Gelert Shake",
  "Borovan Chicken",
  "Cream Cheese Pretzel Bites",
  "Uh Oh, Spaghetti Eyes",
  "Giblets Gravy",
  "Jhudora Day Pastry",
  "Mint Chip Skeith Cone",
  "Rainbow Toast with Rainbow Jam",
  "Vanilla Waffle Cone",
  "Cheesy Slorgwich",
  "Fruit Krawk Pot",
  "Wocky Spaghetti Ball",
  "Garlicy Mushrooms",
  "Aisha Mega Burger",
  "Fancy Star Burger",
  "Lemon Lime Neocola",
  "Sparkling Twirly Fruit Juice",
  "Tofu Pumpkin",
  "Zafara Vegetable Croissant",
  "Illusen Lunch Box",
  "Mighty Grarrl Burger",
  "Chiazilla Quesadilla",
  "Zafara Orange Juice",
  "Baby Shoyru Baby Bottle",
  "Edible Argyle Socks",
  "Veggie Poogle Pate",
  "Ham and Cheese Mashed Potato",
  "Butter Toffee Popcorn",
  "Orange-Stuffed Turkey with Jam Dressing",
  "Peach Milkshake",
  "Cheese Sticks",
  "Boiled Peanut Dash Peanuts",
  "Deep-Fried Candy Floss",
  "Sausage Jacket Potato",
  "Chocolate Techo Foot",
  "Snowy Negg",
  "Sroom Fruit Sandwich",
  "Skull Stew",
  "Steel Negg",
  "Raspberry Cranberry Juice",
  "Refried Beans and Rice",
  "Cheddar and Screlon Plate",
  "Chomby Hot Dog",
  "Dung Negg",
  "Fake Blumaroo Steak",
  "Grarrl Macaroni",
  "Jinjah Maple Mocktail",
  "Lucky Slothy Day Dip",
  "Mutant Hot Dog",
  "Speckled Ice Cream",
  "Yooyuball Pizza",
  "Chestnut Soup",
  "Chocolate Chip Gelert Ice Cream Sandwich",
  "Christmas Quiggle Lettuce and Tomato Wrap",
  "Plain Mashed Potato",
  "Chicken With Vegetables",
  "Hash Browns",
  "Mushrooms On A Stick",
  "Orapple Fizz",
  "Potato-Stuffed Turkey",
  "Furanga Fruit Sandwich",
  "Warm Transparaberry Cocktail",
  "Berry Delight",
  "Bottle of Water",
  "Chocolate Milk",
  "Grey Ice Cream Cone",
  "Orange Flavoured Borovan",
  "Banana Achyfi",
  "Bubbly Rhuby Fruit Juice",
  "Moehog Grilled Peanut Butter Sandwich",
  "Cheese and Raspberry Plate",
  "Sparkling Pink New Year Juice",
  "Strawberry Waffle Cone",
  "Barbecued Meat",
  "Crispy Crunchy Cookies Cereal",
  "Forbidden Forever Fruit",
  "Rangamelon",
  "Turkey Casserole",
  "Cucumber Salad",
  "Flotsam Flakes",
  "Pastrami Milkshake",
  "Skeith Quesadilla",
  "Xweetok Burger",
  "Durian Lupe Treat",
  "Eggs Benedict",
  "Honey Glazed Ham",
  "Nimmo Meatloaf",
  "Symol Extra Cheesy Cheese Ball",
  "Tigerbuggle Jacket Potato",
  "Vegan Turkey Dinner",
  "Aisha Day Soup",
  "Skeith Crisps",
  "Soba Noodles",
  "Doglefox Popcorn",
  "Pineapple Ham",
  "Sparkling Space Cocktail",
  "Caramel Flavoured Kougra Milk",
  "Cheesy Mashed Potato",
  "Edible Orange Socks",
  "Flaming Hot Chips",
  "Grarrl Crackers",
  "Lutaya",
  "Marshmallow Yam Soup",
  "Meaty Chia Soup",
  "Peophin Pancakes",
  "Squid Spaghetti",
  "Super Icy Custard",
  "Jhudora Day Burger",
  "Delicious Borovan Crepe",
  "Fresh Green Salad",
  "Peanut",
  "Shoyru Cereal",
  "Yurble Steak",
  "Scorched Kabob",
  "Chia Chia Pudding",
  "Chocolate Techo Cookie",
  "Fried Eggs and Scallion Tortillas",
  "Grey Peach Pie",
  "Jhudoras Achyfi",
  "Origami Breakfast",
  "Plushie Turkey",
  "Turkey and Chestnut Dressing",
  "Turkey Leg Pasta",
  "Gnorbu Wool Noodles",
  "Grey Cheese",
  "Hairy Fungus Salad",
  "Chocolatey Pork Chops",
  "Garlic Kebab",
  "Kale",
  "Nachos With Cheese",
  "Peanut Butter Crackers",
  "Sausage Cornucopia",
  "Cheesy Onion Sticks",
  "Chicken Curry",
  "Dirt Cheese",
  "French Toast",
  "Hot Doughnutfruit Juice",
  "Krawk Brand Crisps",
  "Limeade",
  "Lupe Soup",
  "Mynci Vegetable Burger",
  "Peanut Butter Bone",
  "Shoyru Spaghetti",
  "Skeith Sundae",
  "Sparkling Sroom Fruit Juice",
  "Turkey Leg",
  "Chokato Chomby Crisps",
  "Turkey Wing Dinner",
  "Date Milkshake",
  "Fresh Durian",
  "Peanut Butter & Jelly JubJub Sandwich",
  "Carrot Salad",
  "Cranberry Fog Drink",
  "JubJub Strawberry Juice",
  "Orange Lupe Treat",
  "Peanut Dash Cookie",
  "Plushie Broccoli",
  "Plushie Burger",
  "Sand Negg",
  "Sloth Day Pasta",
  "Speckled Candy Floss",
  "Mixed Grarrl Salad",
  "Peanut Dash Shake",
  "Brightvale Rigamaroll",
  "Cheddar Fries",
  "Tofukabob",
  "Broccoli",
  "Pat of Butter",
  "Peanut Butter Toast",
  "Plain Shoyru Meatball",
  "Pteri Burger",
  "Strawberry Blumaroo Cone",
  "Spicy Peophin Burger",
  "Bori Cheese Sandwich",
  "Cheery Tomato Soup Bowl",
  "Plain Bagel",
  "Scorched Veggies",
  "Two Garlic Bulbs",
  "Mutant Toast",
  "Berry Smore",
  "Black Currant Milkshake",
  "Bran Boulders",
  "Cheese Stuffed Mushrooms",
  "Chocolate Peanut Butter Bagel",
  "Corn Chowder Soup Bowl",
  "Crimson Ham",
  "Elephante Chicken Nuggets",
  "Elephante Milkshake",
  "Elephante Salad",
  "Fresh Turnip Sandwich",
  "Garlic Bread Halves",
  "Gold Koi Crackers",
  "Jicama",
  "Korbat Tea Sandwiches",
  "Lava Bread",
  "Lava Bread Bowl",
  "Lenny Meaty Burger",
  "Meat Tuskabob",
  "Noil Cracker",
  "Paper Negg",
  "Pea and Carrot-Stuffed Turkey",
  "Ruki Juicebox",
  "Sparkling Suti Fruit Juice",
  "Tchea JubJub Mini Burger",
  "Tofu Poogle Pate",
  "Turkey Croquettes",
  "Mynci Veggie Plate",
];

// List Items 5k - 15k np
const List2 = [
  "Deep-Fried Mac-n-Cheese Loaf",
  "Disco Toast",
  "Jelly Neocola",
  "Jhudora Eyeball Pasta",
  "Pomegranate",
  "Tomato Cannon Ball",
  "Tonu Tonic Water",
  "White Chocolate Covered Toffee",
  "Chokato Sundae",
  "Kyrii Jumbleberry Milkshake",
  "Pirate Pancakes",
  "Sweet and Sour Soup",
  "Peanut Butter Tonu Crackers",
  "Chocolate Chomby Ice Cream Sandwich",
  "Plain Crackers",
  "Raspberry Basket",
  "BLT Sandwich with Cheese",
  "Cheese and Pickle Packed Lunch",
  "Ham Casserole",
  "Gnorbu Chocolate Pudding",
  "Raspberry Scones",
  "Cheddar Kacheek Cheese",
  "Chocolate Gnome Crunch",
  "Cinnamon Apple Chips",
  "Number Jelly Parfait",
  "Black Cherry Taco",
  "Doughnutfruit Punch",
  "Moehog Milkshake",
  "Peanut Butter and Jelly Gormball Sandwich",
  "Paper-Wrapped Veggies",
  "Wintermelon",
  "Swirly Chocolate Milk",
  "A Smatter of Ketchup",
  "Slorg Biscuits",
  "Hearty Pie",
  "Gooseberry Jam Packed Lunch",
  "Seasoned Curly Chips",
  "Peanut Butter Smores",
  "Bori Bowl of Fruit",
  "Double Scoop of Sorbet",
  "Minty Aisha Sundae",
  "Negg Noodle Soup",
  "Pink Triple Decker Sandwich",
  "Valentines Negg",
  "Korbat Veggie Plate",
  "Lutari Pancakes",
  "Pink Cheese",
  "Veal Parmesan Gormball Sandwich",
  "Extra Meaty Sandwich",
  "Korbat Cheese and Crackers",
  "Mini Koi Cereal",
  "Buzz Sandwich With Honey",
  "Dressing and Cranberry Sandwich",
  "Seasoned Lupe Chips",
  "Spicy Purblare Juice",
  "Buzz Dung Cone",
  "Pineapple and Broccoli Pie",
  "Strawberry Oatmeal",
  "Vanilla Skeith Cone",
  "Cheesy Kois",
  "Chips and Egg",
  "Curried Chicken Tea Sandwiches",
  "Mild Cheddar Jetsam Fin Crackers",
  "Techo Foot Sandwich",
  "Tonu Cheeseburger",
  "Cinnamon Toasties",
  "Bubbly Twirly Fruit Juice",
  "Turkey Curry",
  "Fruit Basket",
  "Egg Stew",
  "Strawberry Jetsam Ice Cream",
  "Fruit Punch Roll",
  "Strawberry Ixi Fizzy Drink",
  "Waffle Burger",
  "Continuous Meat",
  "Shiver Me Shrimp",
  "Kadoatie Puffs",
  "Pastrami Gormball Sandwich",
  "Smiley Pancakes",
  "Deceptive Soup",
  "Doglefox Ice Cream Scoops",
  "Extra Meaty Pie",
  "Koi Seaweed Sundae",
  "Morel Mushroom Dip",
  "Number Fruit Leather",
  "Squid Sauce",
  "Acara Rainbow Lollypop",
  "Carrots in Salad",
  "Apple Walnut Tea Sandwiches",
  "Cole Slaw",
  "Grape Juice Sippy Cup",
  "Mayonnaise Chilli and Cheese covered Corn on the Cob",
  "Extra Large Xweetok Sushi",
  "Freeze Dried Meat",
  "Grapefruit Biscuits",
  "Yurble Pot Pie",
  "Elephante Ice Cream",
  "Iced Shoyru Meatball",
  "Bacon Tape",
  "Banana Grub",
  "Deluxe Cheese Fondue",
  "Dorkleshroom",
  "Egg Salad Packed Lunch",
  "Eggy Weggs",
  "Exotic Sliced Truffles",
  "Gnorbu Wool Candy Floss",
  "Grootafruit Punch",
  "Happy Birthday Negg",
  "Hot Fruit Soup",
  "Kacheek Meatball",
  "Lettuce Wrap",
  "Number Pasta",
  "Raspberry Aisha Waffle",
  "Spinach Alfredo Omurice",
  "Crunchy Buzz Honey Delight",
  "Sprinkling of Salt",
  "Grilled Cheese Soup Dippers",
  "Red Scorchipepper",
  "Chocolate Aisha Sundae",
  "A Smatter of Mayo",
  "Caramel Chia Parfait",
  "Vanilla Yurblecone",
  "Banana Roll",
  "Brown Sugar Oatmeal",
  "Raspberry Yurblecone",
  "Disco Ice Cream",
  "Left-Over Sliced Turkey Sandwich",
  "Flowers and Coffee",
  "Paper-Wrapped Salmon",
  "Pickled Pears",
  "Gourmet Grilled Steak Salad",
  "Orange Yurblecone",
  "Chokato Omurice",
  "Fancy Rack of Lamb",
  "Snotty Vira Onion",
  "Cherry Mynci Burger",
  "Strawberry Scorchio Treat",
  "Blue Berry Aisha Ice Cream",
  "Chestnut Shortcake",
  "Snow Lemon",
  "Spicy Kau Burger",
  "Xweetok Sugar Cookies",
  "Tomato Omurice",
  "Pickled Peppers",
  "Quadruple Scoop of Sorbet",
  "Spaghetti Hot Dog",
  "Zafara Veggie Stew",
  "Buzz Bread Salad",
  "Cheesykraut Hot Dog",
  "Doglefox Candy Floss",
  "Sour Cream Chomby Crisps",
  "Tropical Breeze",
  "Bombshroom",
  "Chicken Taquitos",
  "Sausage Gravy",
  "Gingerbread Cookie Box",
  "Kyrii Dewy Apple Milkshake",
  "Caesar Salad",
  "Oatmeal Raisins",
  "Potato Salad",
  "Thing Rolls",
  "Vanilla Poogle Cupcake",
  "Chocolate Poogle Cupcake",
  "Stone Veggie Gormball Sandwich",
  "Bubbly Roseatte Juice",
  "Clam and Meatball Pizza",
  "Flaming Hot Burger",
  "Meridellian Chocolate Milk Glass",
  "Sloth Day Soup",
  "Ogrin Peanut Butter and Jelly Sandwich",
  "Blueberry Jelly Twirl",
  "Fresh Borovan and Asparagus Tart",
  "Dried Lupe Snack",
  "Cheesy Onion Noodle Soup",
  "Blueberry and Orange Blend",
  "Chicken Dumpling Soup",
  "Festive Faerie Fizz",
  "Kyrii Florange Milkshake",
  "Lupe Burger",
  "Mutant Doughnut",
  "Neopia Central Chocolate Milk Glass",
  "Noil Mashed Potatoes",
  "Ogrin Pasta",
  "Star Shaped Cheeseburger",
  "Tall Stack of Mutant Pancakes",
  "Turkey Dumplings",
  "Cheese Negg",
  "Golden Tangerines",
  "Peanut Butter and Jelly Hot Dog",
  "Chocolate Covered Toffee",
  "Egg Pate",
  "Fruity Aisha Sundae",
  "Sketch Pie",
  "Blackberry Sorbet",
  "Lemon and Orange Blend",
  "Symol Cheddar Cheese Ball",
  "Purple Hamburger",
  "Christmas Wocky Cranberry Meatloaf",
  "Snot Fries",
  "Mutant Kau Milkshake",
  "Wormy Jam Sandwich",
  "Blue Bruce Juice",
  "Ham and Mustard Packed Lunch",
  "Low Fat Milk",
  "Salmon Cream Cheese Dip",
  "Twirly Fruit Cream Cheese Dip",
  "Fish Filet Sandwich",
  "Gnome Crunch",
  "Wishbone Delight",
  "Strawberry Parfait",
  "Aisha Tomato and Potato Soup",
  "Sketch Eggs",
  "Tuskaninny Ice Cream",
  "Snot Sandwich",
  "Sour Apple Ixi Fizzy Drink",
  "Bowl Hominy",
  "Dirt Ice Cream",
  "Hot Fudge Sundae",
  "Liver Poogle Pate",
  "Peanut Butter & Jelly Waffle Sandwich",
  "Toast",
  "Fizzy Grape Lupe Drink",
  "Gourmet Fried Chicken and Waffles",
  "Korbat Pasta and Meatballs",
  "Orange Baby Aisha Lollypop",
  "Xweetok Vegetable Soup",
  "Paper-Wrapped Chicken",
  "Symol Mouldy Cheese Ball",
  "Gooey Green Shake",
  "Chocolate Lupe Ice Cream",
  "Vegetarian Usul Wrap",
  "Bowl of Mushy Peas",
  "Cheese and Tonu Crackers",
  "Creamed Corn",
  "Hot Buzz Pie",
  "Neggdrop Soup",
  "Sketch Sandwich",
  "Beef and Veggie Soup",
  "Bubbly Harffel Fruit Juice",
  "Draik Salad",
  "Freeze Dried Bacon",
  "Poogle Pot Pie",
  "Starflower Patterned Easter Negg",
  "Doglefox Cookies",
  "Ixi Acorn Meatball",
  "Uni Corn",
  "Zafara Breakfast",
  "Blueberry Roll",
  "Cherimoya",
  "Cinnamon Neocola",
  "Draik Soup",
  "Gnorbu Wool Burger",
  "Granola Parfait",
  "Sausage and Chips",
  "Small Fizzy Drink",
  "Strawberry Achyfi",
  "Dipping Apples",
  "Quiggle Veggie Soup",
  "Sliced Turkey Dinner",
  "Deep-Fried Okra",
  "Felberry Gormball Sandwich",
  "Number Crackers and Cheese",
  "A Smatter of Mustard",
  "Scorchio Smores",
  "Ixi Double Veggie Burger",
  "Dark Chocolate Covered Toffee",
  "Mynci Fruit Kebab",
];

// List Items 15k - 100k NP
const List3 = [
  "Deluxe Elephante Cake",
  "Glass Negg",
  "Ornate Purple Negg",
  "Zafara Hot Chocolate",
  "Pink Negg",
  "Twirly Fruit Juice",
  "Flotsam Fin Soup",
  "Uni Ice Cream",
  "Tea Biscuits",
  "Twin Salad",
  "Lemon Swirly Negg",
  "Super Icy Negg",
  "Black Cherry Ice Lolly",
  "Kyrii Agueena Milkshake",
  "Mynci Surprise Ice Cream",
  "Lutari Fizz",
  "Cybunny Pancakes",
  "Turkey Drumstick Dinner",
  "Wocky Plum Pudding",
  "Watermelon Roll",
  "Lime Swirly Negg",
  "Green Negg",
  "Cybunny Carrot Stew",
  "Techo Jelly Surprise",
  "Chocolate Ice Cream",
  "Pumpkin Bread",
  "Tomato Baby Food",
  "Buzz Sandwich",
  "Chokato Toffee Apple",
  "Square Marshmallows",
  "Shenkuu Chocolate Milk Glass",
  "Breakfast Cake",
  "Exotic Plant",
  "Squibble Berry Sandwich",
  "Raspberry Baby JubJub Lollypop",
  "Chocolate Shoyru Meatball",
  "Cookie Negg",
  "Unripe Puntec Wrap",
  "Buzz Mashed Potato",
  "Sloth Day Nachos",
  "Chomby Juice",
  "Apple Rigamaroll",
  "Space Station Chocolate Milk Glass",
  "Blue Acara Cake",
  "Flied Rice",
  "Stuffed Chokatos",
  "Meerca Bolognese",
  "Jinjah Ale",
  "White Chocolate Pear",
  "Cream of Tchea Soup",
  "Grilled Islandberry Slices",
  "Congratulations Negg",
  "Honeydew Melon",
  "Knowledge Hungry Burger",
  "Chocolate Elephante Doughnut",
  "Blueberry Jelly Doughnut",
  "Vanilla Neocola",
  "Mosaic Negg",
  "Turnip Eyrie Souffle",
  "Chocolate Poogle Lolly",
  "Fried Something Something",
  "Chocolate Covered Apple",
  "Strawberry Cybunny Ice Cream",
  "Grapeade",
  "Extra Large Fizzy Drink",
  "CPMPB Salad",
  "Uni Crisps",
  "Deep-Fried Vegetables",
  "Shell Lollypop",
  "Thistleberry Sandwich",
  "Negg",
  "Orange Roll",
  "Sketch Sundae",
  "Lemon",
  "Steak Platter",
  "Hot Meerca Tea",
  "Scaled Negg",
  "Double Stuffed Guppy",
  "Nimmo Day Fruit Cake",
  "Slice of Zafara Pizza",
  "Sprinkling of Black Pepper",
  "Turkey Dinner",
  "Egg and Carrots",
  "Orange Jetsam Cupcake",
  "Chocolate Kau Milk",
  "Beef Wellington",
  "Cupid Negg",
  "Lamb Chop",
  "Chunky Mushroom Soup",
  "Fried Potato Balls",
  "Hot Dog on a Stick",
  "Oyster Obsession",
  "Pineapple and Oranges",
  "Dirt Achyfi",
  "Mini Swiss Kau Cheese Wheel",
  "Creamy Jello Jigglers",
  "Lemon Lava Cake",
  "Seaweed Bacon",
  "Caramel Coated Pear",
  "Raspberry Sundae",
  "Pickled Onion",
  "Vanilla Gnorbu Cupcake",
  "Blumaroo Ice Cream Sundae",
  "Chia Cereal",
  "Chocolate Nimmo Dessert",
  "Flotsam Ice Cream Sundae",
  "Green Scorchipepper",
  "Red Buzz Energy Drink",
  "Terror Mountain Chocolate Milk Glass",
  "Crusty Clam Surprise",
  "Cheese Rigamaroll",
  "Snow Enchiladas",
  "Roast Chestnut Neggnog",
  "Baked Avocado with Curried Sauce",
];

// List Items > 100k NP +
const List4 = [
  "Onion and Mustard Pie",
  "Rainbow Cybunny Negg",
  "Mega Sandwich",
  "Big Gulp Neocola",
  "Black Currant Juice",
  "BLT Croissant",
  "Olivetato",
  "Golden Caviar",
  "Egg and Tomato Sandwich",
  "Green Picnic Hamper",
  "Chain of Onions",
  "Polka Carrot",
  "Rainbow Carrot",
  "Chocolate Coated Blue Cheese",
  "Happy Anniversary Negg",
  "Chocolate Coated Cheese",
  "Kadoatie Biscuits",
  "Plum",
  "Mutated Negg",
  "Blue Cybunny Negg",
  "Chocolate Coated Holey Cheese",
  "Glowing Apple",
  "Raspberry Toffee Apple",
  "Tigersquash Custard",
  "Upside Down Ice Cream",
  "Borovan Hot Chocolate Bomb",
  "Fire Apple",
  "Rainbow Apple",
  "Cheesy Strawberry Slice",
  "Bilge Rat Madeira",
  "Blue Picnic Hamper",
  "Capn Threelegs Cutlass Crusade",
  "Cheesy Carrot Chunks",
  "Cheesy Chocoshake",
  "Cheesy Chokato Pie",
  "Cheesy Krawk Dip",
  "Fun Icy Cheese Pop",
  "Honey and Bacon Burger",
  "Ice Apple",
  "Illusens Family Recipe Cake",
  "Invisible Cookie",
  "Lenny Salad",
  "Loretta Fontaines Perfect Pizza",
  "Our Famous Krawk Pie",
  "Puntec Cupcake",
  "Purple Picnic Hamper",
  "Starry Cupcake",
  "Steak Surprise",
  "Tchea Toffee Apple",
  "Pretty Purple Princess Negg",
  "Red Picnic Hamper",
  "Hogshead",
  "Candy Floss Carrot",
  "Flaming Tuskaninny Ice Cream",
  "Headless Horsefish",
  "Meerca Apertif",
  "Mega Tuna Sandwich",
  "Zeenana Toffee Apple",
  "Lawyerbot Degreaser",
  "Carrot Crown",
  "Baby Bloater",
  "Bangers and Mash",
  "Barnacle Bills Belt Busting Burger",
  "Berry Joy Fun Pop",
  "Cannon Fodder",
  "Chocolate Joy Fun Pop",
  "Grape Pop",
  "Rainbow Negg",
  "Island Meatloaf",
  "Krakuberry Cove",
  "Land Lubber",
  "Lemon Pop",
  "Man O War",
  "Slithering Squid Surprise",
  "Starry Scorchipepper",
  "Tchea Grog",
  "ErgyFruit Grog",
  "Krakuberry Grog",
  "Assorted Vandagyre Approved Nuts",
  "Bomberry Grog",
  "Wocky Steak",
  "Blueberry and Oyster Ice Cream",
  "Cherry Pop",
  "Forbidden Plunder",
  "Keel Haul",
  "Mocha Joy Fun Pop",
  "Pinanna Paradise",
  "Raspberry Pop",
  "Le Sausage",
  "Fancy Rack of Lamb with Fruit",
  "Grog Light",
  "Chokato Rigamaroll",
  "Fire Fondue",
  "Walk The Plank",
  "Green Ham",
  "Heart Shaped Negg",
  "Mega Pipper Sandwich",
  "Leftover Shortcrust Pastry",
  "Bag of Peanuts",
  "Spotted Kau Ice Cream",
  "Borovan Layered Cake",
  "Thick Chocolate Soup",
  "Kau Kau Farm Soy Milk",
  "Uni Triple Scoop Rainbow Sorbet",
  "Custard Cheesecake",
  "Seaweed Flotsam Burger",
  "Peach Jelly",
  "Square Meat",
  "Uni Pie",
  "Frozen Veggie Delight",
  "Maple Syrup Negg",
  "Starfish Cake",
  "Xweetok Hot Chocolate",
  "Phear Flavoured Milk",
  "Kau Kau Farm Organic Bottled Milk",
  "Twirly Fruit Toasty",
  "Wheaty Kyrii Sandwich",
  "Sugar Coated Apple Fritters",
  "Twirly Fruit Flavoured Milk",
  "Container of Purple Liquid",
  "Kau Waffles",
  "Watercress Tea Sandwiches",
  "Purple Potato Aperitif",
  "Cheesy Choco Cookie",
  "Tchea Toasty",
  "Spotted Kau Sandwich",
  "Vanilla JubJub Sundae",
  "Jetsam Seafood Soup",
  "Vanilla Flotsam Day Shake",
  "Chocolate Covered Carrot",
  "Chocolate Green Tea Parfait",
  "Grey Juice",
  "Funnydew Neggnog",
  "Thornberry Bagel",
  "Pizza Sandwich",
  "Cucumber Tea Sandwiches",
  "Twirly Fruit Shoyru Ice Cream",
  "Mega Manoroot Sandwich",
  "Baked Juppie",
  "Steak Negg",
  "Borovan Pavlova",
  "Tonu Sorbet",
  "Puzzle Fruit",
  "Borovan Brownies",
  "Strawberry Taco",
  "Tea Waffles",
  "Peppered Salmon Dish",
  "Vanilla Aisha Pudding",
  "French Toast PB&J Sandwich",
  "Fall Leaf Salad",
  "JubJub Coconut Juice",
  "Extra Fancy Crackers",
  "Purple Cybunny Negg",
  "Fire Tonic",
  "Lemonade",
  "Thornberry Gormball Sandwich",
  "Apple Juice Sippy Cup",
  "Tea Jelly",
  "Tonu Orange Juice",
  "Speckled Negg",
  "Harffel Flavoured Milk",
  "Toast on Toast",
  "Suti Jam Triple Decker",
  "Welsh Rarebit",
  "Tarragon Achyfi",
  "Whole Wheat Jetsam Fin Crackers",
  "Bacon Taco",
  "Ruki Salad",
  "Buzz Honey Pot",
  "Vanilla Flavoured Borovan",
  "Chocolate Covered Tomato",
  "Illusen Negg",
  "Petpet Crackers",
  "Xweetok Veggie Crepe",
  "Neopets 18th Birthday Cake",
  "Toffee Chocolate Aisha Sundae",
  "Asparagus Borovan Lasagne",
  "Suspicious Borovan Creame Pie",
  "Techo Energy Drink",
  "Watermelon Maraquan Shoyru",
  "Super Spicy Borovan",
  "Ultimate Icy Negg",
  "Christmas Pattern Negg",
  "Evil Popcorn",
  "Peanut Dash Stir Fry",
  "White Cheddar Jetsam Fin Crackers",
  "Baby Elephante Milk Bottle",
  "Battle Duck Negg",
  "Rock Negg",
  "Vanilla Gelert Ice Cream Sandwich",
  "Sweet and Sour Negg",
  "A Dozen Neggs",
  "Candy Cane Negg",
  "Custard",
  "Purple Negg",
  "Jalapeno Kacheek Cheese",
  "Noil Candy Floss",
  "Partitioned Negg",
  "Vanilla Blumaroo Cone",
  "Tea Infuser",
  "Chokato Neggnog",
  "Decorative Negg",
  "Tasty Guacamole",
  "Fried Negg Sandwich",
  "Diet Big Gulp Neocola",
  "Grey Toast",
  "Orange Negg",
  "Ultra Icy Negg",
  "Yellow Negg",
  "Blue Negg",
  "Watermelon Jetsam",
  "Flower Nectar",
  "Fruit Tart",
  "Thorn on the Cob",
  "Acara Ice Cream Surprise",
  "Black Caviar",
  "Cybunny Day Canape",
  "Puntec Parcel",
  "Pirate Negg",
  "Uni Salad",
  "Donut Burger",
  "Squid on a Stick",
  "Rainbow Neggnog",
  "Deluxe Peophin Burger",
  "Swirly Negg #498",
  "Fire Carrot",
];

// Function to apply styles to items based on the current array
(function() {
    'use strict';
    // Display a Key on page
    // Create the price key div element
    var keyDiv = document.createElement('div');

    // Set styles to make it subtle and fixed to the right side
    keyDiv.style.position = 'fixed';
    keyDiv.style.top = '180px';
    keyDiv.style.right = '3px';
    keyDiv.style.backgroundColor = 'rgba(255, 255, 255, 0.9)';
    keyDiv.style.border = '1px solid #ccc';
    keyDiv.style.padding = '10px';
    keyDiv.style.fontSize = '11px';
    keyDiv.style.fontFamily = 'Arial, sans-serif';
    keyDiv.style.zIndex = '1000';
    keyDiv.style.width = '90px';
    keyDiv.style.maxHeight = '90vh'; // Ensures it doesn't overflow the viewport
    keyDiv.style.overflowY = 'auto'; // Scroll if needed
    keyDiv.style.opacity = '0.4'; // Make it more subtle
    keyDiv.style.transition = 'opacity 0.2s';

    // Hover effect to make it more visible when hovered over
    keyDiv.onmouseover = function() {
        keyDiv.style.opacity = '1';
    };
    keyDiv.onmouseout = function() {
        keyDiv.style.opacity = '0.6';
    };

    // The content of the key with added space and alignment tweaks
    keyDiv.innerHTML = `
    <div style="display: flex; align-items: center;">
    <strong>- Price Key -</strong></center><br><br>
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; background-color: #f1f1f1; margin-right: 5px;"></div>
        < 1,000 np
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; background-color: #fff; margin-right: 5px;"></div>
        1k - 2k
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; border: 1px dotted green; margin-right: 5px;"></div>
        2k - 5k
    </div>
    <div style="display: flex; align-items: center; margin-bottom: 6px;">
        <div style="width: 12px; height: 12px; border: 1px solid orange; margin-right: 5px;"></div>
        5k - 15k
    </div>
    <div style="display: flex; align-items: center;">
        <div style="width: 12px; height: 12px; border: 2px dashed red; margin-right: 5px;"></div>
        15k - 100k
    </div>
    <div style="display: flex; align-items: center;">
        <div style="width: 12px; height: 12px; border: 2px solid red; margin-right: 5px; margin-top: 5px;"></div>
        100k +
    </div>
`;

    // Countdown Element
    let countdownDiv = document.createElement('div');
    countdownDiv.style.marginTop = '10px';
    countdownDiv.style.fontSize = '12px';
    countdownDiv.style.fontWeight = 'bold';
    countdownDiv.style.color = '#333';
    countdownDiv.textContent = 'Countdown: 5';

    keyDiv.appendChild(countdownDiv); // Append countdown below the price key
    document.body.appendChild(keyDiv);

    // Countdown Logic
    let countdown = 5;
    setInterval(() => {
        countdown = countdown === 1 ? 5 : countdown - 1; // Reset to 5 after reaching 1
        countdownDiv.textContent = `Countdown: ${countdown}`;
    }, 1000); // Update every second

// Append the price key div to the body
    document.body.appendChild(keyDiv);
})();

// Tab Colour Change/ Flash

let flashInterval; // Store the interval ID to stop flashing later
let originalTitle = document.title; // Save the original title

// Function to start flashing the tab title
function startFlashingTab() {
    flashInterval = setInterval(() => {
        document.title = document.title === originalTitle ? "⚠️ High-Value Item! ⚠️" : originalTitle;
    }, 500); // Flash every 500ms
}

// Function to stop flashing the tab title
function stopFlashingTab() {
    clearInterval(flashInterval); // Stop the interval
    document.title = originalTitle; // Reset to original title
}


// Function to apply styles to items based on the current array
function applyStylesToItems(itemArray) {
  var itemNames = document.getElementsByClassName("item-name");

  for (var i = 0; i < itemNames.length; i++) {
    var itemName = itemNames[i].textContent.trim();

    if (itemArray.includes(itemName)) {
      // Apply different styles based on the array order
      if (itemArray === List4) {
        // Red Thick Box
        notificationSound.play(); // Play sound
        startFlashingTab(); // Start flashing the tab
        setTimeout(stopFlashingTab, 6000); // Stop flashing after 6 seconds
        itemNames[i].parentNode.style.border = "5px solid red";
        itemNames[i].parentNode.style.padding = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 0, 0, 0.2)";
        itemNames[i].style.color = "red";
        itemNames[i].style.fontWeight = "800";
        itemNames[i].style.textDecoration = "underline";
      } else if (itemArray === List3) {
        // Red Dashed
        notificationSound.play(); // Play sound
        startFlashingTab(); // Start flashing the tab
        setTimeout(stopFlashingTab, 6000); // Stop flashing after 6 seconds
        itemNames[i].parentNode.style.border = "2px dashed red";
        itemNames[i].style.color = "red";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 0, 0, 0.1)";
      } else if (itemArray === List2) {
        // Orange
        itemNames[i].style.color = "orange";
        itemNames[i].parentNode.style.border = "2px solid orange";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(255, 165, 0, 0.2)";
      } else if (itemArray === List1) {
        // Green Dotted
        itemNames[i].style.color = "green";
        itemNames[i].parentNode.style.border = "1px dotted green";
        itemNames[i].parentNode.style.paddingTop = "5px";
        itemNames[i].parentNode.style.boxShadow = "0 4px 8px rgba(0, 255, 0, 0.2)";
      } else if (itemArray === List0) {
        // Light Grey
        itemNames[i].style.color = "lightgrey";
        itemNames[i].style.fontWeight = "200";
        itemNames[i].parentNode.style.paddingTop = "5px";
        var itemImgDiv = itemNames[i].parentNode.querySelector(".item-img");
        if (itemImgDiv) {
          itemImgDiv.style.opacity = "0.2";
        }
      }
    }
  }
}

// Loop through each price array and apply styles
applyStylesToItems(List4);
applyStylesToItems(List3);
applyStylesToItems(List2);
applyStylesToItems(List1);
applyStylesToItems(List0);